version: "3.9"
services:
  webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: ./src/HowTo.WebApp
    ports: 
      - 8090:80
  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build: 
      context: ./src/HowTo.WebApi
    ports:
      - 8091:80
  identityapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: ./src/HowTo.IdentityApi
    ports:
      - 8092:80
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-admin
      MONGO_INITDB_ROOT_PASSWORD: mongo-password
  mongo-exporess:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo-admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo-password
      ME_CONFIG_MONGODB_URL: mongodb://mongo-admin:mongo-password@mongo:27017/