version: "3.9"
services:
  webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: ./src/HowTo.WebApp
    ports: 
      - 8090:80
  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build: 
      context: ./src/HowTo.WebApi
    ports:
      - 8091:80
  identityapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: ./src/HowTo.IdentityApi
    ports:
      - 8092:80
